#import <Foundation/Foundation.h>
#import <QuickLook/QuickLook.h>

NSString *escapeForJS(NSString *str) {
    NSMutableString *escaped = [str mutableCopy];
    [escaped replaceOccurrencesOfString:@"\\" withString:@"\\\\" options:0 range:NSMakeRange(0, escaped.length)];
    [escaped replaceOccurrencesOfString:@"`" withString:@"\\`" options:0 range:NSMakeRange(0, escaped.length)];
    [escaped replaceOccurrencesOfString:@"$" withString:@"\\$" options:0 range:NSMakeRange(0, escaped.length)];
    return [escaped copy];
}

NSString *detectFormat(CFURLRef url) {
    NSString *path = [(__bridge NSURL *)url path];
    NSString *ext = [[path pathExtension] lowercaseString];
    if ([ext isEqualToString:@"owl"]) return @"owl";
    if ([ext isEqualToString:@"rdf"]) return @"rdf";
    if ([ext isEqualToString:@"ttl"]) return @"ttl";
    return @"ttl";
}

NSString *getViewerHTML(void) {
    return @
    "<!DOCTYPE html>\n"
    "<html lang='en'>\n"
    "<head>\n"
    "<meta charset='UTF-8'>\n"
    "<meta name='viewport' content='width=device-width, initial-scale=1.0'>\n"
    "<title>OntoAir - Ontology Viewer</title>\n"
    "<style>\n"
    "*{margin:0;padding:0;box-sizing:border-box}\n"
    "body{background:#fff;overflow:hidden;font-family:'SF Pro',system-ui,-apple-system,sans-serif;color:#333}\n"
    "#hud{position:fixed;top:16px;left:16px;z-index:10;background:rgba(255,255,255,0.94);border:1px solid #e0e0e0;border-radius:10px;padding:16px 20px;min-width:220px;box-shadow:0 2px 12px rgba(0,0,0,0.06)}\n"
    "#hud h2{font-size:13px;font-weight:700;letter-spacing:.3px;margin-bottom:4px}\n"
    "#hud .filename{font-size:11px;color:#999;margin-bottom:8px;word-break:break-all}\n"
    "#hud .info{font-size:11px;color:#666;line-height:1.7}\n"
    "#legend{position:fixed;bottom:16px;left:16px;z-index:10;background:rgba(255,255,255,0.94);border:1px solid #e0e0e0;border-radius:10px;padding:14px 18px;box-shadow:0 2px 12px rgba(0,0,0,0.06)}\n"
    "#legend h3{font-size:10px;color:#aaa;margin-bottom:6px;text-transform:uppercase;letter-spacing:.8px}\n"
    ".leg-item{display:flex;align-items:center;gap:8px;padding:2px 0;font-size:11px;color:#555}\n"
    ".leg-shape{width:18px;height:18px}\n"
    "#tooltip{position:fixed;display:none;z-index:100;background:#fff;border:1px solid #ddd;border-radius:8px;padding:10px 14px;font-size:12px;pointer-events:none;box-shadow:0 4px 16px rgba(0,0,0,0.1);max-width:360px}\n"
    "#tooltip .tt-name{font-weight:700;font-size:13px}\n"
    "#tooltip .tt-type{font-size:10px;color:#999;text-transform:uppercase;letter-spacing:.5px;margin-top:2px}\n"
    "#tooltip .tt-uri{font-size:10px;color:#bbb;margin-top:4px;word-break:break-all}\n"
    "#tooltip .tt-props{margin-top:6px;font-size:11px;color:#666;line-height:1.5}\n"
    "#controls{position:fixed;bottom:16px;right:16px;z-index:10;display:flex;gap:6px}\n"
    "#controls button{background:#fff;border:1px solid #ddd;border-radius:8px;padding:7px 16px;color:#555;font-size:11px;cursor:pointer;transition:all .15s}\n"
    "#controls button:hover{background:#f5f5f5;border-color:#ccc}\n"
    "#controls button.active{background:#333;color:#fff;border-color:#333}\n"
    "#search-box{position:fixed;top:16px;right:16px;z-index:10}\n"
    "#search-box input{background:rgba(255,255,255,0.94);border:1px solid #e0e0e0;border-radius:8px;padding:8px 14px;font-size:12px;width:200px;outline:none;box-shadow:0 2px 8px rgba(0,0,0,0.04)}\n"
    "#search-box input:focus{border-color:#999;box-shadow:0 2px 12px rgba(0,0,0,0.08)}\n"
    "#loading{position:fixed;top:50%;left:50%;transform:translate(-50%,-50%);font-size:14px;color:#aaa;z-index:200}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "\n"
    "<div id='hud'>\n"
    "  <h2>OntoAir</h2>\n"
    "  <div class='filename' id='hud-filename'></div>\n"
    "  <div class='info' id='hud-info'>Loading...</div>\n"
    "</div>\n"
    "\n"
    "<div id='legend'>\n"
    "  <h3>Node Types</h3>\n"
    "  <div class='leg-item'><svg class='leg-shape' viewBox='0 0 18 18'><circle cx='9' cy='9' r='7' fill='#fff' stroke='#333' stroke-width='1.5'/></svg>owl:Class</div>\n"
    "  <div class='leg-item'><svg class='leg-shape' viewBox='0 0 18 18'><polygon points='9,2 16,15 2,15' fill='#fff' stroke='#333' stroke-width='1.5'/></svg>ObjectProperty</div>\n"
    "  <div class='leg-item'><svg class='leg-shape' viewBox='0 0 18 18'><rect x='3' y='3' width='12' height='12' fill='#fff' stroke='#333' stroke-width='1.5'/></svg>DatatypeProperty</div>\n"
    "  <div class='leg-item'><svg class='leg-shape' viewBox='0 0 18 18'><polygon points='9,1 15,9 9,17 3,9' fill='#fff' stroke='#333' stroke-width='1.5'/></svg>Individual</div>\n"
    "  <div class='leg-item'><svg class='leg-shape' viewBox='0 0 18 18'><polygon points='9,1 11,6.5 17,7 13,11 14,17 9,14 4,17 5,11 1,7 6.5,6.5' fill='#fff' stroke='#333' stroke-width='1.5'/></svg>AnnotationProperty</div>\n"
    "  <h3 style='margin-top:8px'>Edge Types</h3>\n"
    "  <div class='leg-item'><span style='width:30px;border-top:2px solid #333;display:inline-block'></span>subClassOf</div>\n"
    "  <div class='leg-item'><span style='width:30px;border-top:2px solid #999;display:inline-block'></span>domain / range</div>\n"
    "  <div class='leg-item'><span style='width:30px;border-top:1px dashed #bbb;display:inline-block'></span>rdf:type</div>\n"
    "</div>\n"
    "\n"
    "<div id='tooltip'>\n"
    "  <div class='tt-name'></div>\n"
    "  <div class='tt-type'></div>\n"
    "  <div class='tt-uri'></div>\n"
    "  <div class='tt-props'></div>\n"
    "</div>\n"
    "\n"
    "<div id='search-box'><input type='text' id='search' placeholder='Search nodes...'></div>\n"
    "\n"
    "<div id='controls'>\n"
    "  <button id='btn-hier' class='active'>Hierarchy</button>\n"
    "  <button id='btn-force'>Force</button>\n"
    "  <button id='btn-reset'>Reset</button>\n"
    "</div>\n"
    "\n"
    "<div id='loading'>Parsing ontology...</div>\n"
    "\n"
    "<script type='importmap'>\n"
    "{\"imports\":{\"three\":\"https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js\",\"three/addons/\":\"https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/\"}}\n"
    "</script>\n"
    "<script type='module'>\n"
    "import * as THREE from 'three';\n"
    "import { OrbitControls } from 'three/addons/controls/OrbitControls.js';\n"
    "\n"
    "// ===== ONTOLOGY DATA (injected by OntoAir) =====\n"
    "const RAW_CONTENT = ONTOAIR_RAW_CONTENT;\n"
    "const FILE_FORMAT = ONTOAIR_FILE_FORMAT;\n"
    "const FILE_NAME = ONTOAIR_FILE_NAME;\n"
    "\n"
    "// ===== PARSER =====\n"
    "function localName(uri) {\n"
    "  if (!uri) return '';\n"
    "  const h = uri.lastIndexOf('#');\n"
    "  const s = uri.lastIndexOf('/');\n"
    "  return uri.substring(Math.max(h, s) + 1);\n"
    "}\n"
    "\n"
    "function parseOWLXML(xml) {\n"
    "  const parser = new DOMParser();\n"
    "  const doc = parser.parseFromString(xml, 'application/xml');\n"
    "  const result = { classes: [], objProps: [], dtProps: [], annProps: [], individuals: [], subClassOf: [], domains: [], ranges: [], types: [], triples: [] };\n"
    "\n"
    "  const ns = {\n"
    "    owl: 'http://www.w3.org/2002/07/owl#',\n"
    "    rdf: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',\n"
    "    rdfs: 'http://www.w3.org/2000/01/rdf-schema#',\n"
    "    xml: 'http://www.w3.org/XML/1998/namespace'\n"
    "  };\n"
    "\n"
    "  function getAbout(el) {\n"
    "    return el.getAttributeNS(ns.rdf, 'about') || el.getAttributeNS(ns.rdf, 'ID') || el.getAttribute('rdf:about') || el.getAttribute('rdf:ID') || '';\n"
    "  }\n"
    "  function getResource(el) {\n"
    "    return el.getAttributeNS(ns.rdf, 'resource') || el.getAttribute('rdf:resource') || '';\n"
    "  }\n"
    "\n"
    "  // Collect all elements\n"
    "  const allElements = doc.querySelectorAll('*');\n"
    "  const seen = new Set();\n"
    "\n"
    "  allElements.forEach(el => {\n"
    "    const tag = el.localName;\n"
    "    const nsURI = el.namespaceURI;\n"
    "    const about = getAbout(el);\n"
    "    const name = localName(about);\n"
    "\n"
    "    // owl:Class\n"
    "    if ((tag === 'Class' && (nsURI === ns.owl || !nsURI)) || el.tagName === 'owl:Class') {\n"
    "      if (about && !seen.has('c:'+name)) { seen.add('c:'+name); result.classes.push({ id: name, uri: about }); }\n"
    "      // Check for rdfs:subClassOf children\n"
    "      el.querySelectorAll('subClassOf, [rdf\\\\:resource]').forEach(sub => {\n"
    "        if (sub.localName === 'subClassOf' || sub.tagName === 'rdfs:subClassOf') {\n"
    "          const parent = getResource(sub);\n"
    "          if (parent) result.subClassOf.push([name, localName(parent)]);\n"
    "        }\n"
    "      });\n"
    "      // Direct rdfs:subClassOf children\n"
    "      for (const ch of el.children) {\n"
    "        if (ch.localName === 'subClassOf' || ch.tagName === 'rdfs:subClassOf') {\n"
    "          const parent = getResource(ch);\n"
    "          if (parent) result.subClassOf.push([name, localName(parent)]);\n"
    "        }\n"
    "      }\n"
    "    }\n"
    "\n"
    "    // owl:ObjectProperty\n"
    "    if ((tag === 'ObjectProperty' && (nsURI === ns.owl || !nsURI)) || el.tagName === 'owl:ObjectProperty') {\n"
    "      if (about && !seen.has('op:'+name)) { seen.add('op:'+name); result.objProps.push({ id: name, uri: about }); }\n"
    "      for (const ch of el.children) {\n"
    "        if (ch.localName === 'domain' || ch.tagName === 'rdfs:domain') {\n"
    "          const r = getResource(ch); if (r) result.domains.push({ prop: name, cls: localName(r) });\n"
    "        }\n"
    "        if (ch.localName === 'range' || ch.tagName === 'rdfs:range') {\n"
    "          const r = getResource(ch); if (r) result.ranges.push({ prop: name, cls: localName(r) });\n"
    "        }\n"
    "      }\n"
    "    }\n"
    "\n"
    "    // owl:DatatypeProperty\n"
    "    if ((tag === 'DatatypeProperty' && (nsURI === ns.owl || !nsURI)) || el.tagName === 'owl:DatatypeProperty') {\n"
    "      if (about && !seen.has('dp:'+name)) { seen.add('dp:'+name); result.dtProps.push({ id: name, uri: about }); }\n"
    "      for (const ch of el.children) {\n"
    "        if (ch.localName === 'domain' || ch.tagName === 'rdfs:domain') {\n"
    "          const r = getResource(ch); if (r) result.domains.push({ prop: name, cls: localName(r) });\n"
    "        }\n"
    "        if (ch.localName === 'range' || ch.tagName === 'rdfs:range') {\n"
    "          const r = getResource(ch); if (r) result.ranges.push({ prop: name, cls: localName(r) });\n"
    "        }\n"
    "      }\n"
    "    }\n"
    "\n"
    "    // owl:AnnotationProperty\n"
    "    if ((tag === 'AnnotationProperty' && (nsURI === ns.owl || !nsURI)) || el.tagName === 'owl:AnnotationProperty') {\n"
    "      if (about && !seen.has('ap:'+name)) { seen.add('ap:'+name); result.annProps.push({ id: name, uri: about }); }\n"
    "    }\n"
    "\n"
    "    // owl:NamedIndividual\n"
    "    if ((tag === 'NamedIndividual' && (nsURI === ns.owl || !nsURI)) || el.tagName === 'owl:NamedIndividual') {\n"
    "      if (about && !seen.has('i:'+name)) {\n"
    "        seen.add('i:'+name);\n"
    "        let cls = '';\n"
    "        for (const ch of el.children) {\n"
    "          if (ch.localName === 'type' || ch.tagName === 'rdf:type') {\n"
    "            const r = getResource(ch); if (r && !r.includes('NamedIndividual')) cls = localName(r);\n"
    "          }\n"
    "        }\n"
    "        result.individuals.push({ id: name, uri: about, cls });\n"
    "        if (cls) result.types.push([name, cls]);\n"
    "      }\n"
    "    }\n"
    "\n"
    "    // rdf:Description with rdf:type\n"
    "    if (tag === 'Description' || el.tagName === 'rdf:Description') {\n"
    "      if (about) {\n"
    "        for (const ch of el.children) {\n"
    "          if (ch.localName === 'type' || ch.tagName === 'rdf:type') {\n"
    "            const r = getResource(ch);\n"
    "            if (r) {\n"
    "              const typeName = localName(r);\n"
    "              if (typeName === 'Class' && !seen.has('c:'+name)) { seen.add('c:'+name); result.classes.push({ id: name, uri: about }); }\n"
    "              else if (typeName === 'ObjectProperty' && !seen.has('op:'+name)) { seen.add('op:'+name); result.objProps.push({ id: name, uri: about }); }\n"
    "              else if (typeName === 'DatatypeProperty' && !seen.has('dp:'+name)) { seen.add('dp:'+name); result.dtProps.push({ id: name, uri: about }); }\n"
    "              else if (!seen.has('i:'+name)) {\n"
    "                seen.add('i:'+name);\n"
    "                result.individuals.push({ id: name, uri: about, cls: typeName });\n"
    "                result.types.push([name, typeName]);\n"
    "              }\n"
    "            }\n"
    "          }\n"
    "          if (ch.localName === 'subClassOf' || ch.tagName === 'rdfs:subClassOf') {\n"
    "            const r = getResource(ch); if (r) result.subClassOf.push([name, localName(r)]);\n"
    "          }\n"
    "          if (ch.localName === 'domain' || ch.tagName === 'rdfs:domain') {\n"
    "            const r = getResource(ch); if (r) result.domains.push({ prop: name, cls: localName(r) });\n"
    "          }\n"
    "          if (ch.localName === 'range' || ch.tagName === 'rdfs:range') {\n"
    "            const r = getResource(ch); if (r) result.ranges.push({ prop: name, cls: localName(r) });\n"
    "          }\n"
    "        }\n"
    "      }\n"
    "    }\n"
    "  });\n"
    "\n"
    "  // Also check for standalone subClassOf at top level\n"
    "  allElements.forEach(el => {\n"
    "    if (el.localName === 'subClassOf' || el.tagName === 'rdfs:subClassOf') {\n"
    "      const parent = el.parentElement;\n"
    "      if (parent) {\n"
    "        const childName = localName(getAbout(parent));\n"
    "        const parentName = localName(getResource(el));\n"
    "        if (childName && parentName && !result.subClassOf.some(s => s[0]===childName && s[1]===parentName)) {\n"
    "          result.subClassOf.push([childName, parentName]);\n"
    "        }\n"
    "      }\n"
    "    }\n"
    "  });\n"
    "\n"
    "  return result;\n"
    "}\n"
    "\n"
    "function parseTurtle(ttl) {\n"
    "  const result = { classes: [], objProps: [], dtProps: [], annProps: [], individuals: [], subClassOf: [], domains: [], ranges: [], types: [], triples: [] };\n"
    "  const prefixes = {};\n"
    "  const seen = new Set();\n"
    "\n"
    "  // Remove comments\n"
    "  const lines = ttl.split('\\n').map(l => l.replace(/#(?![<]).*$/, '').trim()).filter(l => l);\n"
    "  const content = lines.join(' ');\n"
    "\n"
    "  // Parse prefixes\n"
    "  const prefixRe = /@prefix\\s+(\\w*):?\\s*<([^>]+)>\\s*\\./g;\n"
    "  let pm;\n"
    "  while ((pm = prefixRe.exec(content))) prefixes[pm[1]] = pm[2];\n"
    "  // Also PREFIX (SPARQL style)\n"
    "  const prefixRe2 = /PREFIX\\s+(\\w*):?\\s*<([^>]+)>/gi;\n"
    "  while ((pm = prefixRe2.exec(content))) prefixes[pm[1]] = pm[2];\n"
    "\n"
    "  function expandURI(curie) {\n"
    "    if (!curie) return '';\n"
    "    if (curie.startsWith('<') && curie.endsWith('>')) return curie.slice(1, -1);\n"
    "    const i = curie.indexOf(':');\n"
    "    if (i >= 0) {\n"
    "      const prefix = curie.substring(0, i);\n"
    "      const local = curie.substring(i + 1);\n"
    "      if (prefixes[prefix] !== undefined) return prefixes[prefix] + local;\n"
    "    }\n"
    "    return curie;\n"
    "  }\n"
    "\n"
    "  function resolveName(curie) {\n"
    "    return localName(expandURI(curie));\n"
    "  }\n"
    "\n"
    "  // Remove prefix declarations from content\n"
    "  let body = content.replace(/@prefix\\s+\\w*:?\\s*<[^>]+>\\s*\\./g, '').replace(/PREFIX\\s+\\w*:?\\s*<[^>]+>/gi, '').trim();\n"
    "  // Also remove @base\n"
    "  body = body.replace(/@base\\s*<[^>]+>\\s*\\./g, '').trim();\n"
    "\n"
    "  // Split into statements (by '.')\n"
    "  // Handle nested brackets [...] and quoted strings\n"
    "  const statements = [];\n"
    "  let depth = 0, qchar = null, stmt = '';\n"
    "  for (let i = 0; i < body.length; i++) {\n"
    "    const c = body[i];\n"
    "    if (qchar) { stmt += c; if (c === qchar && body[i-1] !== '\\\\') qchar = null; continue; }\n"
    "    if (c === '\"' || c === \"'\") { qchar = c; stmt += c; continue; }\n"
    "    if (c === '[' || c === '(') { depth++; stmt += c; continue; }\n"
    "    if (c === ']' || c === ')') { depth--; stmt += c; continue; }\n"
    "    if (c === '.' && depth === 0) { if (stmt.trim()) statements.push(stmt.trim()); stmt = ''; continue; }\n"
    "    stmt += c;\n"
    "  }\n"
    "  if (stmt.trim()) statements.push(stmt.trim());\n"
    "\n"
    "  // Parse each statement into triples\n"
    "  statements.forEach(st => {\n"
    "    // Split by ';' for same-subject triples\n"
    "    const parts = st.split(/\\s*;\\s*/);\n"
    "    if (parts.length === 0) return;\n"
    "\n"
    "    // First part has subject\n"
    "    const firstTokens = parts[0].match(/\\S+/g);\n"
    "    if (!firstTokens || firstTokens.length < 2) return;\n"
    "    const subject = firstTokens[0];\n"
    "\n"
    "    function processPredicateObject(tokens) {\n"
    "      if (tokens.length < 2) return;\n"
    "      const pred = tokens[0];\n"
    "      // Handle ',' for multiple objects\n"
    "      const objects = tokens.slice(1).join(' ').split(/\\s*,\\s*/);\n"
    "      objects.forEach(obj => {\n"
    "        obj = obj.trim();\n"
    "        if (!obj) return;\n"
    "        const s = resolveName(subject), p = expandURI(pred), o = resolveName(obj);\n"
    "        const pLocal = localName(p);\n"
    "\n"
    "        result.triples.push({ s: expandURI(subject), p, o: expandURI(obj) });\n"
    "\n"
    "        if (pred === 'a' || p.endsWith('#type')) {\n"
    "          const typeURI = expandURI(obj);\n"
    "          const typeName = localName(typeURI);\n"
    "          if (typeName === 'Class' || typeName === 'Class') {\n"
    "            if (!seen.has('c:'+s)) { seen.add('c:'+s); result.classes.push({ id: s, uri: expandURI(subject) }); }\n"
    "          } else if (typeName === 'ObjectProperty') {\n"
    "            if (!seen.has('op:'+s)) { seen.add('op:'+s); result.objProps.push({ id: s, uri: expandURI(subject) }); }\n"
    "          } else if (typeName === 'DatatypeProperty') {\n"
    "            if (!seen.has('dp:'+s)) { seen.add('dp:'+s); result.dtProps.push({ id: s, uri: expandURI(subject) }); }\n"
    "          } else if (typeName === 'AnnotationProperty') {\n"
    "            if (!seen.has('ap:'+s)) { seen.add('ap:'+s); result.annProps.push({ id: s, uri: expandURI(subject) }); }\n"
    "          } else if (typeName === 'Ontology' || typeName === 'Restriction') {\n"
    "            // skip\n"
    "          } else if (typeName === 'NamedIndividual') {\n"
    "            // Will be typed by another triple\n"
    "          } else {\n"
    "            if (!seen.has('i:'+s)) { seen.add('i:'+s); result.individuals.push({ id: s, uri: expandURI(subject), cls: typeName }); }\n"
    "            result.types.push([s, typeName]);\n"
    "          }\n"
    "        } else if (pLocal === 'subClassOf') {\n"
    "          result.subClassOf.push([s, o]);\n"
    "        } else if (pLocal === 'domain') {\n"
    "          result.domains.push({ prop: s, cls: o });\n"
    "        } else if (pLocal === 'range') {\n"
    "          result.ranges.push({ prop: s, cls: o });\n"
    "        }\n"
    "      });\n"
    "    }\n"
    "\n"
    "    // Process first part (skip subject)\n"
    "    processPredicateObject(firstTokens.slice(1));\n"
    "    // Process remaining parts (same subject)\n"
    "    for (let i = 1; i < parts.length; i++) {\n"
    "      const tokens = parts[i].match(/\\S+/g);\n"
    "      if (tokens) processPredicateObject(tokens);\n"
    "    }\n"
    "  });\n"
    "\n"
    "  return result;\n"
    "}\n"
    "\n"
    "function parseOntology(content, format) {\n"
    "  if (format === 'ttl') return parseTurtle(content);\n"
    "  return parseOWLXML(content);\n"
    "}\n"
    "\n"
    "// ===== PARSE =====\n"
    "const onto = parseOntology(RAW_CONTENT, FILE_FORMAT);\n"
    "document.getElementById('loading').style.display = 'none';\n"
    "\n"
    "// ===== THREE.JS SETUP =====\n"
    "const canvas = document.createElement('canvas');\n"
    "document.body.appendChild(canvas);\n"
    "const renderer = new THREE.WebGLRenderer({ canvas, antialias: true });\n"
    "renderer.setSize(innerWidth, innerHeight);\n"
    "renderer.setPixelRatio(Math.min(devicePixelRatio, 2));\n"
    "renderer.setClearColor(0xffffff);\n"
    "\n"
    "const scene = new THREE.Scene();\n"
    "const camera = new THREE.PerspectiveCamera(50, innerWidth / innerHeight, 0.1, 800);\n"
    "camera.position.set(0, 20, 55);\n"
    "\n"
    "const ctrl = new OrbitControls(camera, canvas);\n"
    "ctrl.enableDamping = true;\n"
    "ctrl.dampingFactor = 0.05;\n"
    "\n"
    "scene.add(new THREE.AmbientLight(0xffffff, 1));\n"
    "const dirLight = new THREE.DirectionalLight(0xffffff, 0.3);\n"
    "dirLight.position.set(10, 20, 10);\n"
    "scene.add(dirLight);\n"
    "\n"
    "// ===== SHAPE GEOMETRIES =====\n"
    "function circGeo(r) { return new THREE.CircleGeometry(r, 32); }\n"
    "function triGeo(r) { const s = new THREE.Shape(); s.moveTo(0, r); s.lineTo(-r * .87, -r * .5); s.lineTo(r * .87, -r * .5); s.closePath(); return new THREE.ShapeGeometry(s); }\n"
    "function sqGeo(r) { const s = new THREE.Shape(), h = r * .8; s.moveTo(-h, -h); s.lineTo(h, -h); s.lineTo(h, h); s.lineTo(-h, h); s.closePath(); return new THREE.ShapeGeometry(s); }\n"
    "function diaGeo(r) { const s = new THREE.Shape(); s.moveTo(0, r); s.lineTo(r * .7, 0); s.lineTo(0, -r); s.lineTo(-r * .7, 0); s.closePath(); return new THREE.ShapeGeometry(s); }\n"
    "function starGeo(r) { const s = new THREE.Shape(); for (let i = 0; i < 5; i++) { const oa = i * 2 * Math.PI / 5 - Math.PI / 2, ia = oa + Math.PI / 5; if (!i) s.moveTo(Math.cos(oa) * r, Math.sin(oa) * r); else s.lineTo(Math.cos(oa) * r, Math.sin(oa) * r); s.lineTo(Math.cos(ia) * r * .45, Math.sin(ia) * r * .45); } s.closePath(); return new THREE.ShapeGeometry(s); }\n"
    "\n"
    "const GEO = {\n"
    "  Class: circGeo(1.2),\n"
    "  ObjectProperty: triGeo(1.1),\n"
    "  DatatypeProperty: sqGeo(1.1),\n"
    "  AnnotationProperty: starGeo(1.1),\n"
    "  Individual: diaGeo(1.1)\n"
    "};\n"
    "\n"
    "// ===== LAYOUT =====\n"
    "const nodeMap = {};\n"
    "const nodeMeshes = [];\n"
    "const edgeObjs = [];\n"
    "\n"
    "function hierLayout() {\n"
    "  const topClasses = onto.classes.filter(c => !onto.subClassOf.some(s => s[0] === c.id));\n"
    "  const subClasses = onto.classes.filter(c => onto.subClassOf.some(s => s[0] === c.id));\n"
    "\n"
    "  // Scale radius based on total node count\n"
    "  const totalNodes = onto.classes.length + onto.objProps.length + onto.dtProps.length + onto.annProps.length + onto.individuals.length;\n"
    "  const baseR = Math.max(12, Math.sqrt(totalNodes) * 4);\n"
    "\n"
    "  topClasses.forEach((c, i) => {\n"
    "    const angle = i / Math.max(topClasses.length, 1) * Math.PI * 2;\n"
    "    nodeMap[c.id] = { x: Math.cos(angle) * baseR, y: 5, z: Math.sin(angle) * baseR };\n"
    "  });\n"
    "\n"
    "  subClasses.forEach((c, i) => {\n"
    "    const parentId = onto.subClassOf.find(s => s[0] === c.id)?.[1];\n"
    "    const p = nodeMap[parentId];\n"
    "    if (p) {\n"
    "      const angle = i / Math.max(subClasses.length, 1) * Math.PI * 2;\n"
    "      nodeMap[c.id] = { x: p.x + Math.cos(angle) * 5, y: p.y - 5, z: p.z + Math.sin(angle) * 5 };\n"
    "    } else {\n"
    "      const angle = i / Math.max(subClasses.length, 1) * Math.PI * 2;\n"
    "      nodeMap[c.id] = { x: Math.cos(angle) * baseR * 0.6, y: 0, z: Math.sin(angle) * baseR * 0.6 };\n"
    "    }\n"
    "  });\n"
    "\n"
    "  // Properties positioned between domain/range\n"
    "  const allProps = [...onto.objProps.map(p => ({ ...p, t: 'ObjectProperty' })), ...onto.dtProps.map(p => ({ ...p, t: 'DatatypeProperty' })), ...onto.annProps.map(p => ({ ...p, t: 'AnnotationProperty' }))];\n"
    "  allProps.forEach((prop, i) => {\n"
    "    const domEntry = onto.domains.find(d => d.prop === prop.id);\n"
    "    const ranEntry = onto.ranges.find(r => r.prop === prop.id);\n"
    "    const d = domEntry ? nodeMap[domEntry.cls] : null;\n"
    "    const r = ranEntry ? nodeMap[ranEntry.cls] : null;\n"
    "    if (d && r) {\n"
    "      nodeMap[prop.id] = { x: (d.x + r.x) / 2 + (Math.random() - .5) * 3, y: (d.y + r.y) / 2 - 3, z: (d.z + r.z) / 2 + (Math.random() - .5) * 3 };\n"
    "    } else if (d) {\n"
    "      nodeMap[prop.id] = { x: d.x + (Math.random() - .5) * 6, y: d.y - 4, z: d.z + (Math.random() - .5) * 6 };\n"
    "    } else {\n"
    "      const angle = i / Math.max(allProps.length, 1) * Math.PI * 2;\n"
    "      nodeMap[prop.id] = { x: Math.cos(angle) * (baseR + 8), y: -8, z: Math.sin(angle) * (baseR + 8) };\n"
    "    }\n"
    "  });\n"
    "\n"
    "  // Individuals near their class\n"
    "  onto.individuals.forEach((inst, i) => {\n"
    "    const p = nodeMap[inst.cls];\n"
    "    if (p) {\n"
    "      const angle = i / Math.max(onto.individuals.length, 1) * Math.PI * 2;\n"
    "      nodeMap[inst.id] = { x: p.x + Math.cos(angle) * 5, y: p.y - 7, z: p.z + Math.sin(angle) * 5 };\n"
    "    } else {\n"
    "      const angle = i / Math.max(onto.individuals.length, 1) * Math.PI * 2;\n"
    "      nodeMap[inst.id] = { x: Math.cos(angle) * (baseR + 14), y: -12, z: Math.sin(angle) * (baseR + 14) };\n"
    "    }\n"
    "  });\n"
    "}\n"
    "\n"
    "hierLayout();\n"
    "\n"
    "// ===== SPRITE TEXT =====\n"
    "function makeLabel(text, size) {\n"
    "  size = size || 0.5;\n"
    "  const c = document.createElement('canvas'); c.width = 512; c.height = 64;\n"
    "  const x = c.getContext('2d');\n"
    "  x.font = 'bold 26px system-ui, -apple-system, sans-serif';\n"
    "  x.fillStyle = '#333'; x.textAlign = 'center'; x.textBaseline = 'middle';\n"
    "  // Truncate long labels\n"
    "  let label = text;\n"
    "  if (label.length > 24) label = label.substring(0, 22) + '...';\n"
    "  x.fillText(label, 256, 32);\n"
    "  const t = new THREE.CanvasTexture(c);\n"
    "  const m = new THREE.SpriteMaterial({ map: t, transparent: true, depthWrite: false });\n"
    "  const s = new THREE.Sprite(m);\n"
    "  s.scale.set(size * 8, size, 1);\n"
    "  return s;\n"
    "}\n"
    "\n"
    "// ===== CREATE NODES =====\n"
    "function makeNode(id, type, x, y, z, label, uri) {\n"
    "  const geo = GEO[type] || GEO.Class;\n"
    "  const mesh = new THREE.Mesh(geo, new THREE.MeshBasicMaterial({ color: 0xffffff, side: THREE.DoubleSide }));\n"
    "  mesh.position.set(x, y, z);\n"
    "  mesh.userData = { id, type, label: label || id, uri: uri || '' };\n"
    "  const eg = new THREE.EdgesGeometry(geo);\n"
    "  mesh.add(new THREE.LineSegments(eg, new THREE.LineBasicMaterial({ color: 0x333333 })));\n"
    "  const lbl = makeLabel(label || id, 0.4);\n"
    "  lbl.position.set(0, -1.6, 0);\n"
    "  mesh.add(lbl);\n"
    "  scene.add(mesh);\n"
    "  nodeMeshes.push(mesh);\n"
    "  return mesh;\n"
    "}\n"
    "\n"
    "// Build nodes\n"
    "onto.classes.forEach(c => { const p = nodeMap[c.id]; if (p) makeNode(c.id, 'Class', p.x, p.y, p.z, c.id, c.uri); });\n"
    "onto.objProps.forEach(c => { const p = nodeMap[c.id]; if (p) makeNode(c.id, 'ObjectProperty', p.x, p.y, p.z, c.id, c.uri); });\n"
    "onto.dtProps.forEach(c => { const p = nodeMap[c.id]; if (p) makeNode(c.id, 'DatatypeProperty', p.x, p.y, p.z, c.id, c.uri); });\n"
    "onto.annProps.forEach(c => { const p = nodeMap[c.id]; if (p) makeNode(c.id, 'AnnotationProperty', p.x, p.y, p.z, c.id, c.uri); });\n"
    "onto.individuals.forEach(c => { const p = nodeMap[c.id]; if (p) makeNode(c.id, 'Individual', p.x, p.y, p.z, c.id, c.uri); });\n"
    "\n"
    "// ===== CREATE EDGES =====\n"
    "function addEdge(srcId, tgtId, label, dashed, color) {\n"
    "  const srcMesh = nodeMeshes.find(m => m.userData.id === srcId);\n"
    "  const tgtMesh = nodeMeshes.find(m => m.userData.id === tgtId);\n"
    "  if (!srcMesh || !tgtMesh) return;\n"
    "  const geo = new THREE.BufferGeometry().setFromPoints([srcMesh.position.clone(), tgtMesh.position.clone()]);\n"
    "  const mat = new THREE.LineBasicMaterial({ color: color || 0xbbbbbb });\n"
    "  if (dashed) { /* solid fallback for compatibility */ }\n"
    "  const line = new THREE.Line(geo, mat);\n"
    "  line.userData = { srcId, tgtId, label };\n"
    "  scene.add(line);\n"
    "  edgeObjs.push(line);\n"
    "  if (label) {\n"
    "    const mid = srcMesh.position.clone().add(tgtMesh.position).multiplyScalar(0.5);\n"
    "    const lbl = makeLabel(label, 0.25);\n"
    "    lbl.position.copy(mid);\n"
    "    scene.add(lbl);\n"
    "    line.userData.labelSprite = lbl;\n"
    "  }\n"
    "}\n"
    "\n"
    "// subClassOf\n"
    "onto.subClassOf.forEach(([child, parent]) => addEdge(child, parent, 'subClassOf', false, 0x333333));\n"
    "// domain\n"
    "onto.domains.forEach(d => addEdge(d.prop, d.cls, 'domain', false, 0x888888));\n"
    "// range\n"
    "onto.ranges.forEach(r => addEdge(r.prop, r.cls, 'range', false, 0x888888));\n"
    "// rdf:type\n"
    "onto.types.forEach(([inst, cls]) => addEdge(inst, cls, 'a', true, 0xaaaaaa));\n"
    "\n"
    "// ===== INTERACTION =====\n"
    "const raycaster = new THREE.Raycaster();\n"
    "const mouse = new THREE.Vector2();\n"
    "const tooltip = document.getElementById('tooltip');\n"
    "let hovered = null;\n"
    "\n"
    "canvas.addEventListener('mousemove', e => {\n"
    "  mouse.x = (e.clientX / innerWidth) * 2 - 1;\n"
    "  mouse.y = -(e.clientY / innerHeight) * 2 + 1;\n"
    "  raycaster.setFromCamera(mouse, camera);\n"
    "  const hits = raycaster.intersectObjects(nodeMeshes);\n"
    "  if (hits.length && hits[0].object.userData.id) {\n"
    "    const d = hits[0].object.userData;\n"
    "    tooltip.style.display = 'block';\n"
    "    tooltip.style.left = (e.clientX + 14) + 'px';\n"
    "    tooltip.style.top = (e.clientY + 14) + 'px';\n"
    "    tooltip.querySelector('.tt-name').textContent = d.label;\n"
    "    tooltip.querySelector('.tt-type').textContent = d.type;\n"
    "    tooltip.querySelector('.tt-uri').textContent = d.uri || d.id;\n"
    "    // Show connections\n"
    "    const conns = edgeObjs.filter(e => e.userData.srcId === d.id || e.userData.tgtId === d.id);\n"
    "    const connText = conns.map(e => {\n"
    "      const other = e.userData.srcId === d.id ? e.userData.tgtId : e.userData.srcId;\n"
    "      return (e.userData.label || '?') + ' -> ' + other;\n"
    "    }).join('<br>');\n"
    "    tooltip.querySelector('.tt-props').innerHTML = connText || 'No connections';\n"
    "    if (hovered && hovered !== hits[0].object) hovered.material.color.setHex(0xffffff);\n"
    "    hovered = hits[0].object;\n"
    "    hovered.material.color.setHex(0xf0f0f0);\n"
    "    // Highlight connected edges\n"
    "    edgeObjs.forEach(e => {\n"
    "      if (e.userData.srcId === d.id || e.userData.tgtId === d.id) e.material.color.setHex(0x333333);\n"
    "      else e.material.color.setHex(e.material._origColor || 0xbbbbbb);\n"
    "    });\n"
    "  } else {\n"
    "    if (hovered) hovered.material.color.setHex(0xffffff);\n"
    "    hovered = null;\n"
    "    tooltip.style.display = 'none';\n"
    "    edgeObjs.forEach(e => e.material.color.setHex(e.material._origColor || 0xbbbbbb));\n"
    "  }\n"
    "});\n"
    "\n"
    "// Store original edge colors\n"
    "edgeObjs.forEach(e => e.material._origColor = e.material.color.getHex());\n"
    "\n"
    "// ===== SEARCH =====\n"
    "document.getElementById('search').addEventListener('input', e => {\n"
    "  const q = e.target.value.toLowerCase();\n"
    "  nodeMeshes.forEach(m => {\n"
    "    if (!q) { m.visible = true; return; }\n"
    "    m.visible = m.userData.label.toLowerCase().includes(q) || m.userData.id.toLowerCase().includes(q);\n"
    "  });\n"
    "  edgeObjs.forEach(line => {\n"
    "    if (!q) { line.visible = true; if (line.userData.labelSprite) line.userData.labelSprite.visible = true; return; }\n"
    "    const sv = nodeMeshes.find(m => m.userData.id === line.userData.srcId)?.visible;\n"
    "    const tv = nodeMeshes.find(m => m.userData.id === line.userData.tgtId)?.visible;\n"
    "    line.visible = sv && tv;\n"
    "    if (line.userData.labelSprite) line.userData.labelSprite.visible = line.visible;\n"
    "  });\n"
    "});\n"
    "\n"
    "// ===== ANIMATE =====\n"
    "function animate() {\n"
    "  requestAnimationFrame(animate);\n"
    "  nodeMeshes.forEach(m => m.quaternion.copy(camera.quaternion));\n"
    "  ctrl.update();\n"
    "  renderer.render(scene, camera);\n"
    "}\n"
    "animate();\n"
    "\n"
    "// ===== FORCE LAYOUT =====\n"
    "function forceLayout(iter) {\n"
    "  iter = iter || 300;\n"
    "  const allIds = Object.keys(nodeMap);\n"
    "  const allEdges = [];\n"
    "  onto.subClassOf.forEach(([c, p]) => allEdges.push([c, p]));\n"
    "  onto.domains.forEach(d => allEdges.push([d.prop, d.cls]));\n"
    "  onto.ranges.forEach(r => allEdges.push([r.prop, r.cls]));\n"
    "  onto.types.forEach(([i, c]) => allEdges.push([i, c]));\n"
    "\n"
    "  allIds.forEach(id => { nodeMap[id].vx = 0; nodeMap[id].vy = 0; nodeMap[id].vz = 0; });\n"
    "  const k = 15;\n"
    "  for (let t = 0; t < iter; t++) {\n"
    "    for (let i = 0; i < allIds.length; i++) {\n"
    "      for (let j = i + 1; j < allIds.length; j++) {\n"
    "        const a = nodeMap[allIds[i]], b = nodeMap[allIds[j]];\n"
    "        const dx = a.x - b.x, dy = a.y - b.y, dz = a.z - b.z;\n"
    "        const d = Math.sqrt(dx * dx + dy * dy + dz * dz) + 0.1;\n"
    "        const f = k * k / d * 0.008;\n"
    "        a.vx += dx / d * f; a.vy += dy / d * f; a.vz += dz / d * f;\n"
    "        b.vx -= dx / d * f; b.vy -= dy / d * f; b.vz -= dz / d * f;\n"
    "      }\n"
    "    }\n"
    "    allEdges.forEach(([s, tgt]) => {\n"
    "      const a = nodeMap[s], b = nodeMap[tgt]; if (!a || !b) return;\n"
    "      const dx = b.x - a.x, dy = b.y - a.y, dz = b.z - a.z;\n"
    "      const d = Math.sqrt(dx * dx + dy * dy + dz * dz) + 0.1;\n"
    "      const f = (d - k * 2) * 0.003;\n"
    "      a.vx += dx / d * f; a.vy += dy / d * f; a.vz += dz / d * f;\n"
    "      b.vx -= dx / d * f; b.vy -= dy / d * f; b.vz -= dz / d * f;\n"
    "    });\n"
    "    allIds.forEach(id => {\n"
    "      const n = nodeMap[id];\n"
    "      n.x += n.vx * 0.5; n.y += n.vy * 0.5; n.z += n.vz * 0.5;\n"
    "      n.vx *= 0.85; n.vy *= 0.85; n.vz *= 0.85;\n"
    "    });\n"
    "  }\n"
    "  applyPositions();\n"
    "}\n"
    "\n"
    "function applyPositions() {\n"
    "  Object.keys(nodeMap).forEach(id => {\n"
    "    const m = nodeMeshes.find(m => m.userData.id === id);\n"
    "    if (m) m.position.set(nodeMap[id].x, nodeMap[id].y, nodeMap[id].z);\n"
    "  });\n"
    "  edgeObjs.forEach(line => {\n"
    "    const s = nodeMeshes.find(m => m.userData.id === line.userData.srcId);\n"
    "    const t = nodeMeshes.find(m => m.userData.id === line.userData.tgtId);\n"
    "    if (s && t) {\n"
    "      const pos = line.geometry.attributes.position;\n"
    "      pos.setXYZ(0, s.position.x, s.position.y, s.position.z);\n"
    "      pos.setXYZ(1, t.position.x, t.position.y, t.position.z);\n"
    "      pos.needsUpdate = true;\n"
    "      if (line.userData.labelSprite) line.userData.labelSprite.position.copy(s.position.clone().add(t.position).multiplyScalar(0.5));\n"
    "    }\n"
    "  });\n"
    "}\n"
    "\n"
    "// ===== CONTROLS =====\n"
    "document.getElementById('btn-force').addEventListener('click', () => {\n"
    "  forceLayout(400);\n"
    "  document.getElementById('btn-hier').classList.remove('active');\n"
    "  document.getElementById('btn-force').classList.add('active');\n"
    "});\n"
    "document.getElementById('btn-hier').addEventListener('click', () => {\n"
    "  hierLayout(); applyPositions();\n"
    "  document.getElementById('btn-hier').classList.add('active');\n"
    "  document.getElementById('btn-force').classList.remove('active');\n"
    "});\n"
    "document.getElementById('btn-reset').addEventListener('click', () => {\n"
    "  camera.position.set(0, 20, 55); ctrl.target.set(0, 0, 0);\n"
    "  document.getElementById('btn-hier').click();\n"
    "});\n"
    "\n"
    "window.addEventListener('resize', () => {\n"
    "  camera.aspect = innerWidth / innerHeight;\n"
    "  camera.updateProjectionMatrix();\n"
    "  renderer.setSize(innerWidth, innerHeight);\n"
    "});\n"
    "\n"
    "// ===== HUD =====\n"
    "document.getElementById('hud-filename').textContent = FILE_NAME;\n"
    "document.getElementById('hud-info').innerHTML =\n"
    "  onto.classes.length + ' owl:Class<br>' +\n"
    "  onto.objProps.length + ' ObjectProperty<br>' +\n"
    "  onto.dtProps.length + ' DatatypeProperty<br>' +\n"
    "  onto.annProps.length + ' AnnotationProperty<br>' +\n"
    "  onto.individuals.length + ' Individual<br>' +\n"
    "  onto.subClassOf.length + ' subClassOf<br>' +\n"
    "  edgeObjs.length + ' edges';\n"
    "\n"
    "// Auto-adjust camera based on node count\n"
    "const totalN = nodeMeshes.length;\n"
    "if (totalN > 50) camera.position.set(0, 30, 80);\n"
    "if (totalN > 100) camera.position.set(0, 40, 120);\n"
    "</script>\n"
    "</body>\n"
    "</html>\n";
}

OSStatus GeneratePreviewForURL(void *thisInterface, QLPreviewRequestRef preview,
                                CFURLRef url, CFStringRef contentTypeUTI,
                                CFDictionaryRef options) {
    (void)thisInterface;
    (void)contentTypeUTI;
    (void)options;

    @autoreleasepool {
        if (QLPreviewRequestIsCancelled(preview)) return noErr;

        // Read ontology file
        NSError *error = nil;
        NSString *content = [NSString stringWithContentsOfURL:(__bridge NSURL *)url
                                                     encoding:NSUTF8StringEncoding
                                                        error:&error];
        if (!content) {
            content = [NSString stringWithContentsOfURL:(__bridge NSURL *)url
                                               encoding:NSISOLatin1StringEncoding
                                                  error:&error];
        }
        if (!content) return noErr;

        if (QLPreviewRequestIsCancelled(preview)) return noErr;

        // Detect format and get filename
        NSString *format = detectFormat(url);
        NSString *fileName = [(__bridge NSURL *)url lastPathComponent];

        // Escape content for JavaScript embedding
        NSString *escaped = escapeForJS(content);

        // Build HTML
        NSString *template = getViewerHTML();

        // Inject data placeholders
        NSString *html = [template stringByReplacingOccurrencesOfString:@"ONTOAIR_RAW_CONTENT"
                                                            withString:[NSString stringWithFormat:@"`%@`", escaped]];
        html = [html stringByReplacingOccurrencesOfString:@"ONTOAIR_FILE_FORMAT"
                                              withString:[NSString stringWithFormat:@"'%@'", format]];
        html = [html stringByReplacingOccurrencesOfString:@"ONTOAIR_FILE_NAME"
                                              withString:[NSString stringWithFormat:@"'%@'", fileName]];

        // Return HTML to QuickLook
        NSDictionary *props = @{
            (__bridge NSString *)kQLPreviewPropertyTextEncodingNameKey: @"UTF-8",
            (__bridge NSString *)kQLPreviewPropertyMIMETypeKey: @"text/html"
        };

        QLPreviewRequestSetDataRepresentation(preview,
            (__bridge CFDataRef)[html dataUsingEncoding:NSUTF8StringEncoding],
            kUTTypeHTML,
            (__bridge CFDictionaryRef)props);
    }

    return noErr;
}

OSStatus GenerateThumbnailForURL(void *thisInterface, QLThumbnailRequestRef thumbnail,
                                  CFURLRef url, CFStringRef contentTypeUTI,
                                  CFDictionaryRef options, CGSize maxSize) {
    (void)thisInterface;
    (void)thumbnail;
    (void)url;
    (void)contentTypeUTI;
    (void)options;
    (void)maxSize;
    return noErr;
}
